version: "3.7"

services:
  main_database:
    image: postgres
    container_name: mytwitter-db
    ports:
      - "5432:5432"
    volumes:
      - "mytwitter-db:/var/lib/postgresql/data"
      - "./ddl.sql:/docker-entrypoint-initdb.d/1.sql:ro"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - TZ=UTC
      - PGTZ=UTC
volumes:
  mytwitter-db: